import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillGithub, AiFillApi, AiFillCode, AiFillHtml5,} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/Theo-logo.png';
import ReactLogo from '../public/react.png';
import PassingThoughts from '../public/passingthoughtscanva.jpeg';
import WeatherApp from '../public/weatherapp.jpeg';
import {useState} from "react";
import WeatherAppi from '../public/Components/WeatherApp';
import SurfBackground from '../public/silvalde 4.jpeg';
import ThoughtPlanner from '../public/Components/ThoughtPlanner';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    

    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Theo Scott Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10  md:px-20 lg:px-40 dark:bg-gray-900" >
        <section className="min-h-screen ">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons text-gray-600 dark:text-white">THEO SCOTT</h1>
          <ul className="flex items-center dark:text-white">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
            </li>
            <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 " href="https://github.com/PestoTrader" target="_blank" rel="noreferrer">Github</a></li>
          </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white">Theo Scott</h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-600 dark:text-white">Front End Developer, Designer</h3>
          
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 
        ">
            
            <a href="https://www.linkedin.com/in/theodore-scott-14a39326/" target="_blank" rel="noreferrer"><AiFillLinkedin /> </a>
            <a href="https://github.com/PestoTrader" target="_blank" rel="noreferrer"><AiFillGithub/></a> 
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-30 md:h-96 md:w-96">
            <Image src={deved} layout="fill" />
          </div>
        </section>

        <section>
          
          <div className="lg:flex gap-10 mx-auto" >
            <div className="text-center shadow-lg p-10 rounded-xl my-10 mx-auto">
              <div className="text-8xl w-100 h-100 flex justify-center gap-16 py-3 text-gray-600 
        " >
              <AiFillCode />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-600 dark:text-white">Front-End-Dev: React</h3>
              <p className="text-gray-600 py-1 dark:text-white">HTML, CSS, Javascript, React, Next, Vue, Sanity</p>
              <p className="py-2 text-gray-600 font-light max-w-3xl text-justify dark:text-white" >Creating app like websites using React tech, using state and effect hooks to create applications and APIs that can update and provide services not available through typical website builders.</p>
            </div>
          </div>
        </section>
        <section>
        
        <div className="lg:flex gap-10 mx-auto" >
            <div className="text-center shadow-lg p-10 rounded-xl my-10 mx-auto">
            
              <h3 className="text-3xl py-1 text-gray-600 dark:text-white">Portfolio</h3>  
              <p className="text-md text-justify py-2 leading-8 text-gray-600 max-w-3xl mx-auto font-light dark:text-white">Here you will find my portfolio work. The Weather App shows API integration using axios and sends get requests to a free weather service. Try entering a city name and clicking return. The Forgetful Thoughts App shows the use of function components used with state and effect hooks to create thoughts that will be erased after 15 seconds.  </p>
            </div> 
            </div>
        </section>
        <section>
            <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10  my-10 sm:my-0 md:basis-1/2 bg-gradient-to-b from-cyan-500 to-teal-500 rounded-lg" >
                  <div>
                  <p >Weather App</p>
                  <WeatherAppi className="rounded-lg  " />
                  
                  </div>
                </div>
                <div className="text-center shadow-lg p-10  my-10 sm:my-0  md:basis-1/2 bg-gradient-to-b from-cyan-500 to-teal-500 rounded-lg" >
                  <div> 
                  <p>Forgetful Thoughts App</p>              
                  <ThoughtPlanner className="rounded-lg " />
                  
                  </div>  
                </div>
              </div>
        </section>
      </main>    
    </div>
  )
}
