import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillGithub, AiFillApi, AiFillCode, AiFillHtml5,} from 'react-icons/ai';
import Image from "next/image";
import deved from '../public/Theo-logo.png';
import ReactLogo from '../public/react.png';
import PassingThoughts from '../public/passingthoughtscanva.jpeg';
import WeatherAppBg from '../public/weatherapp.jpeg';
import {useState} from "react";
import WeatherAppi from '../public/Components/WeatherApp';
import SurfBackground from '../public/silvalde 4.jpeg';
import ThoughtPlanner from '../public/Components/ThoughtPlanner';
import Ecommerce from "../public/Components/Ecommerce";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    

    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title className="font-montserrat">Theo Scott Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10  md:px-20 lg:px-40 dark:bg-gray-900" >
        <section className="min-h-screen ">
        <nav className="py-5 mb-12 flex justify-between">
          <h1 className="text-xl font-montserrat text-gray-600 dark:text-white">THEO SCOTT</h1>
          <ul className="flex items-center dark:text-white">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
            </li>
            <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 font-montserrat rounded-md ml-8 " href="https://github.com/PestoTrader" target="_blank" rel="noreferrer">Github</a></li>
          </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-light md:text-6xl font-montserrat dark:text-white">Theo Scott</h2>
            <h3 className="py-2 font-medium text-sm text-gray-600 font-montserrat dark:text-white">FRONT END DEVELOPER, UI & UX DESIGNER</h3>
          
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 
        ">
            
            <a href="https://www.linkedin.com/in/theodore-scott-14a39326/" target="_blank" rel="noreferrer"><AiFillLinkedin /> </a>
            <a href="https://github.com/PestoTrader" target="_blank" rel="noreferrer"><AiFillGithub/></a> 
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-30 md:h-96 md:w-96">
            <Image src={deved} layout="fill" />
          </div>
        </section>

        <section>
          
          <div className="lg:flex gap-10 mx-auto" >
            <div className="text-center shadow-lg p-10 rounded-xl my-10 mx-auto">
              <div className="text-8xl w-100 h-100 flex justify-center gap-16 py-3 text-gray-600 
        " >
              <AiFillCode />
              </div>
              <h3 className="text-small font-medium pt-8 pb-2 text-gray-600 font-montserrat dark:text-white">Front-End-Dev</h3>
              <p className="text-gray-600 py-1 dark:text-white font-montserrat text-lg ">HTML, CSS, Javascript, React, Next, Vue, Sanity</p>
              <p className="py-2 text-gray-600 font-light text-lg max-w-3xl font-montserrat text-center dark:text-white" >Creating app like websites using React tech, using state and effect hooks to create applications and APIs that can update and provide services not available through typical website builders.</p>
            </div>
          </div>
        </section>
        <section>
          <div> <h3 className="py-5 font-light text-5xl text-center font-montserrat text-gray-600 dark:text-white">Portfolio</h3></div>
        
      
        </section>
        <section>
            <div className="lg:flex gap-10">
            <div>
                  <div className="py-3">
                    <div>
                      <p className=" p-10 text-gray-600 font-montserrat font-light text-lg max-w-3xl text-center dark:text-white">The Weather App shows API integration using axios and sends get requests to a free weather service. Try entering a city name and clicking return.</p>
                    </div>
                    <div className=" text-center h-660 font-montserrat shadow-lg p-10  my-10 sm:my-0  md:basis-1/2 bg-gradient-to-b from-[#06B6D3] to-[#13B7A7] rounded-lg" > <p >Weather App</p>
                  <WeatherAppi className="rounded-lg  " />
                  </div>
                 
                  </div>
                </div>
                <div >
                  <div className="py-3"> 
                    <div>
                      <p className=" p-10 font-montserrat text-gray-600 font-light text-lg max-w-3xl text-center dark:text-white" > The Forgetful Thoughts App shows the use of function components used with state and effect hooks to create thoughts that will be erased after 15 seconds.</p>
                    </div>
                    <div className=" text-center h-660 font-montserrat shadow-lg p-10  my-10 sm:my-0 md:basis-1/2 bg-gradient-to-b from-[#C09FBA]
 to-[#F8BD86] rounded-lg" ><p>Forgetful Thoughts App</p>              
                  <ThoughtPlanner className="rounded-lg " />
                  </div>
                  
                  </div>  
                </div>
              </div>
              <div className="lg:flex gap-10 mx-auto" >
            <div className="text-center shadow-lg p-10 rounded-xl my-10 mx-auto" >
              <div className="text-8xl w-100 h-100 flex justify-center gap-16 py-3 text-gray-600 
        " >
          <div  className=" text-center font-montserrat  p-10  my-10 rounded-lg">
          <p  className="text-gray-600">Ecommerce Project</p>
         <Ecommerce />
         <p className=" font-montserrat text-gray-600 font-light text-lg max-w-5xl text-center dark:text-white" > This e-commerce store was made using Next JS combined with Sanity to create a front and back end system in one. A client could be provided with access to Sanity CMS and add new products and change the banners and this would dynamically change the site and add new product pages. The payment page is currently connected to a test service provided by Stripe and will work upon entering 4242 continuosly as card number details.</p>
         <a type="button" href="https://ecommerce-sanity-build.vercel.app" target="_blank" className="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center font-montserrat mr-2 mb-2">VISIT STORE</a>
         </div>
  
          </div>
          </div>
          </div>


        
        </section>

      </main>    
    </div>
  )
}
